// Conversation compression + background memory extraction for the Megsy
// chat agent. Both run alongside the main agent loop without adding a new
// edge function — they reuse the same DashScope key the loop already has.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
import { embedText, toPgVector } from "../embeddings.ts";

const DASHSCOPE_URL = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions";

const COMPRESS_THRESHOLD_CHARS = 60_000;
const KEEP_RECENT_TURNS = 8;

interface AnyMsg {
  role?: string;
  content?: unknown;
}

function textOf(content: unknown): string {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content
      .map((p: any) => p?.text || p?.content || "")
      .filter(Boolean)
      .join(" ");
  }
  return "";
}

function totalChars(messages: AnyMsg[]): number {
  let n = 0;
  for (const m of messages) n += textOf(m.content).length;
  return n;
}

/**
 * If the conversation is huge, replace the middle turns with a compact
 * summary generated by qwen-turbo. The system message (index 0) and the
 * last KEEP_RECENT_TURNS user/assistant turns stay untouched.
 *
 * Returns the (possibly shortened) message array. On any error, returns
 * the original array — compression is best-effort.
 */
export async function maybeCompressHistory(
  messages: AnyMsg[],
  dashscopeKey: string,
): Promise<AnyMsg[]> {
  try {
    if (totalChars(messages) < COMPRESS_THRESHOLD_CHARS) return messages;

    // Separate: leading system messages | middle | last N turns.
    let leadingSystem = 0;
    while (leadingSystem < messages.length && messages[leadingSystem]?.role === "system") {
      leadingSystem++;
    }
    if (messages.length - leadingSystem <= KEEP_RECENT_TURNS + 2) return messages;

    const head = messages.slice(0, leadingSystem);
    const tail = messages.slice(messages.length - KEEP_RECENT_TURNS);
    const middle = messages.slice(leadingSystem, messages.length - KEEP_RECENT_TURNS);
    if (middle.length === 0) return messages;

    const transcript = middle
      .map((m) => `${m.role || "user"}: ${textOf(m.content).slice(0, 4000)}`)
      .join("\n");

    const r = await fetch(DASHSCOPE_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${dashscopeKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "qwen-turbo",
        stream: false,
        temperature: 0.2,
        max_tokens: 900,
        messages: [
          {
            role: "system",
            content:
              "You compress chat history. Produce a tight third-person summary in the SAME LANGUAGE as the transcript, capturing: user's stable facts/preferences, decisions made, open questions, and any artifacts/links produced. Bullet list. No fluff.",
          },
          { role: "user", content: transcript.slice(0, 50_000) },
        ],
      }),
    });
    if (!r.ok) return messages;
    const data = (await r.json().catch(() => null)) as any;
    const summary = data?.choices?.[0]?.message?.content;
    if (typeof summary !== "string" || !summary.trim()) return messages;

    const summaryMsg: AnyMsg = {
      role: "system",
      content: `<conversation_summary>\nEarlier ${middle.length} turns of this conversation, summarised:\n${summary.trim()}\n</conversation_summary>`,
    };
    console.log(`[compress] ${middle.length} turns → 1 summary (${summary.length} chars)`);
    return [...head, summaryMsg, ...tail];
  } catch (e) {
    console.warn("[compress] failed, using original", e);
    return messages;
  }
}

/**
 * Fire-and-forget: ask qwen-turbo whether the last user turn contains a
 * durable fact about the user (name, role, preference, ongoing project).
 * If yes, save it to user_memory_entries with an embedding. If not, no-op.
 *
 * Designed to run in EdgeRuntime.waitUntil after the stream closes so the
 * user never waits for it.
 */
export async function extractAndSaveMemory(opts: {
  dashscopeKey: string;
  supabaseUrl: string;
  serviceRoleKey: string;
  userId: string;
  messages: AnyMsg[];
}): Promise<void> {
  const { dashscopeKey, supabaseUrl, serviceRoleKey, userId, messages } = opts;
  try {
    // Respect the user's memory toggle. If they paused memory in
    // Settings → Memory, do not extract or save anything.
    const adminEarly = createClient(supabaseUrl, serviceRoleKey, {
      auth: { persistSession: false, autoRefreshToken: false },
    });
    const { data: prof } = await adminEarly
      .from("user_memory_profiles")
      .select("preferences")
      .eq("user_id", userId)
      .maybeSingle();
    if (prof && (prof as any)?.preferences?.enabled === false) {
      return;
    }

    // Grab the last user message + the preceding assistant turn for context.
    let lastUserIdx = -1;
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i]?.role === "user") {
        lastUserIdx = i;
        break;
      }
    }
    if (lastUserIdx < 0) return;
    const userText = textOf(messages[lastUserIdx].content).trim();
    if (!userText || userText.length < 12) return;

    // Cheap classifier + extractor in one call.
    const r = await fetch(DASHSCOPE_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${dashscopeKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "qwen-turbo",
        stream: false,
        temperature: 0,
        max_tokens: 200,
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content: `You decide whether a user's chat message contains a DURABLE personal fact worth remembering across future conversations (name, role/job, location, language, ongoing project, strong preference, important relationship, accessibility need).
Return JSON only:
{"save": true|false, "title": "<≤60 chars>", "summary": "<one sentence stating the fact>"}

Save = false for: questions, tasks, transient requests, opinions about external things, code, anything time-limited.
Save = true ONLY when the user is sharing something stable about themselves.
Summary must be in the user's language.`,
          },
          { role: "user", content: userText.slice(0, 2000) },
        ],
      }),
    });
    if (!r.ok) return;
    const data = (await r.json().catch(() => null)) as any;
    const raw = data?.choices?.[0]?.message?.content;
    if (typeof raw !== "string") return;
    let parsed: any;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return;
    }
    if (!parsed?.save) return;

    const title = String(parsed.title || "")
      .trim()
      .slice(0, 200);
    const summary = String(parsed.summary || "")
      .trim()
      .slice(0, 2000);
    if (!title || !summary) return;

    // Dedupe: if a very similar memory already exists, skip.
    const admin = createClient(supabaseUrl, serviceRoleKey, {
      auth: { persistSession: false, autoRefreshToken: false },
    });
    let embeddingLiteral: string | null = null;
    try {
      const vec = await embedText(`${title}\n${summary}`);
      if (vec) {
        embeddingLiteral = toPgVector(vec);
        const { data: matches } = await admin.rpc("match_user_memories", {
          p_user_id: userId,
          p_query_embedding: embeddingLiteral as any,
          p_match_count: 1,
          p_min_similarity: 0.92,
        });
        if (Array.isArray(matches) && matches.length > 0) {
          console.log("[bg-memory] skipped (duplicate of existing memory)");
          return;
        }
      }
    } catch (e) {
      console.warn("[bg-memory] embed failed, saving without vector", e);
    }

    const row: Record<string, unknown> = {
      user_id: userId,
      title,
      summary,
      scope: "chat_auto",
    };
    if (embeddingLiteral) row.embedding = embeddingLiteral;
    const { error } = await admin.from("user_memory_entries").insert(row);
    if (error) console.warn("[bg-memory] insert failed", error.message);
    else console.log(`[bg-memory] saved: ${title}`);
  } catch (e) {
    console.warn("[bg-memory] failed", e);
  }
}
