INSERT INTO public.video_models (
  slug,
  display_name,
  provider,
  model_id_api,
  endpoint_text_to_video,
  endpoint_image_to_video,
  credits_per_second,
  credits_per_video,
  unit,
  default_aspect,
  default_duration,
  default_resolution,
  supported_aspects,
  supported_durations,
  supported_resolutions,
  supports_audio,
  supports_start_end_frame,
  supports_multi_image,
  max_input_images,
  is_premium,
  is_featured,
  is_new,
  sort_order,
  api_version,
  billing_mode
) VALUES (
  'hailuo-pro',
  'Hailuo Pro',
  'minimax',
  'hailuo/hailuo-pro',
  '/api/v1/services/aigc/video-generation/video-synthesis',
  '/api/v1/services/aigc/video-generation/video-synthesis',
  30,
  null,
  'second',
  '16:9',
  6,
  '720p',
  '["16:9", "9:16", "1:1", "4:3", "3:4"]'::jsonb,
  '[5, 8, 10, 15]'::jsonb,
  '["720p", "1080p"]'::jsonb,
  false,
  false,
  false,
  1,
  true,
  false,
  true,
  99,
  'v2',
  'credit_based'
);