
-- 1) Deactivate every non-Alibaba image model (Aether/Renderful etc.) so only Alibaba + WaveSpeed remain.
UPDATE public.image_models
SET is_active = false, updated_at = now()
WHERE provider <> 'alibaba';

-- 2) Insert top WaveSpeed image models (latest as of June 2026).
INSERT INTO public.image_models
  (slug, display_name, provider, description, unit_cost_usd, credits, model_id_api,
   supports_image_editing, supports_text_rendering, supports_multi_image, max_input_images,
   supported_aspects, supported_resolutions, default_aspect, default_resolution, max_resolution,
   is_premium, is_new, is_featured, sort_order, is_active, endpoint_text_to_image, endpoint_image_to_image)
VALUES
  ('ws-gemini-3-pro-image', 'Gemini 3 Pro Image', 'wavespeed',
    'Google Gemini 3 Pro Image — highest quality T2I with Search grounding.', 0.14, 14,
    'google/nano-banana-pro/text-to-image', true, true, true, 4,
    '["1:1","3:2","2:3","16:9","9:16","4:3","3:4"]'::jsonb, '["1K","2K","4K"]'::jsonb, '1:1', '2K', '4K',
    true, true, true, 10, true, '/api/v3/google/nano-banana-pro/text-to-image', '/api/v3/google/nano-banana-pro/edit'),
  ('ws-nano-banana-2', 'Nano Banana 2', 'wavespeed',
    'Gemini 3.1 Flash Image — fast, sharp T2I + editing.', 0.07, 7,
    'google/nano-banana-2/text-to-image', true, true, true, 4,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, true, true, 20, true, '/api/v3/google/nano-banana-2/text-to-image', '/api/v3/google/nano-banana-2/edit'),
  ('ws-gpt-image-2', 'GPT Image 2', 'wavespeed',
    'OpenAI GPT Image 2 — thinking image model, text-accurate visuals.', 0.06, 6,
    'openai/gpt-image-2/text-to-image', true, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    true, true, true, 30, true, '/api/v3/openai/gpt-image-2/text-to-image', '/api/v3/openai/gpt-image-2/edit'),
  ('ws-gpt-image-1-5', 'GPT Image 1.5', 'wavespeed',
    'OpenAI GPT Image 1.5 — fast and reliable for production.', 0.04, 4,
    'openai/gpt-image-1.5/text-to-image', true, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, false, false, 40, true, '/api/v3/openai/gpt-image-1.5/text-to-image', '/api/v3/openai/gpt-image-1.5/edit'),
  ('ws-seedream-5-lite', 'Seedream 5 Lite', 'wavespeed',
    'ByteDance Seedream 5.0 Lite — newest fast & cheap T2I.', 0.035, 4,
    'bytedance/seedream-v5.0-lite', true, true, true, 3,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, true, true, 50, true, '/api/v3/bytedance/seedream-v5.0-lite', '/api/v3/bytedance/seedream-v5.0-lite/edit'),
  ('ws-seedream-4-5', 'Seedream 4.5', 'wavespeed',
    'ByteDance Seedream 4.5 — strong stylization + editing.', 0.04, 4,
    'bytedance/seedream-v4.5', true, true, true, 3,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, false, true, 60, true, '/api/v3/bytedance/seedream-v4.5', '/api/v3/bytedance/seedream-v4.5/edit'),
  ('ws-flux-2-max', 'FLUX.2 Max', 'wavespeed',
    'Black Forest Labs FLUX.2 Max — top quality, up to 10 refs.', 0.07, 7,
    'wavespeed-ai/flux-2-max/text-to-image', true, true, true, 10,
    '["1:1","3:2","2:3","16:9","9:16","4:3","3:4"]'::jsonb, '["1K","2K","4K"]'::jsonb, '1:1', '2K', '4K',
    true, true, true, 70, true, '/api/v3/wavespeed-ai/flux-2-max/text-to-image', '/api/v3/wavespeed-ai/flux-2-max/edit'),
  ('ws-flux-2-pro', 'FLUX.2 Pro', 'wavespeed',
    'FLUX.2 Pro — commercial-grade T2I + editing.', 0.03, 3,
    'wavespeed-ai/flux-2-pro/text-to-image', true, true, true, 4,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, false, true, 80, true, '/api/v3/wavespeed-ai/flux-2-pro/text-to-image', '/api/v3/wavespeed-ai/flux-2-pro/edit'),
  ('ws-flux-kontext-max', 'FLUX Kontext Max', 'wavespeed',
    'FLUX Kontext Max — best image editing + typography.', 0.08, 8,
    'wavespeed-ai/flux-kontext-max', true, true, true, 4,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    true, false, false, 90, true, '/api/v3/wavespeed-ai/flux-kontext-max', '/api/v3/wavespeed-ai/flux-kontext-max'),
  ('ws-flux-kontext-pro', 'FLUX Kontext Pro', 'wavespeed',
    'FLUX Kontext Pro — image editing pro tier.', 0.04, 4,
    'wavespeed-ai/flux-kontext-pro', true, true, true, 4,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, false, false, 100, true, '/api/v3/wavespeed-ai/flux-kontext-pro', '/api/v3/wavespeed-ai/flux-kontext-pro'),
  ('ws-imagen-4-ultra', 'Imagen 4 Ultra', 'wavespeed',
    'Google Imagen 4 Ultra — premium photorealistic T2I.', 0.058, 6,
    'google/imagen4-ultra', false, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    true, false, false, 110, true, '/api/v3/google/imagen4-ultra', null),
  ('ws-imagen-4', 'Imagen 4', 'wavespeed',
    'Google Imagen 4 — balanced quality + speed.', 0.038, 4,
    'google/imagen4', false, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, false, false, 120, true, '/api/v3/google/imagen4', null),
  ('ws-ideogram-v4', 'Ideogram V4', 'wavespeed',
    'Ideogram V4 — best-in-class text rendering on images.', 0.07, 7,
    'ideogram-ai/ideogram-v4', true, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, true, true, 130, true, '/api/v3/ideogram-ai/ideogram-v4', '/api/v3/ideogram-ai/ideogram-v4/edit'),
  ('ws-recraft-v4-1-pro', 'Recraft V4.1 Pro', 'wavespeed',
    'Recraft V4.1 Pro — brand illustration + vector.', 0.25, 25,
    'recraft-ai/recraft-v4.1-pro/text-to-image', false, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    true, false, false, 140, true, '/api/v3/recraft-ai/recraft-v4.1-pro/text-to-image', null),
  ('ws-recraft-v4-1', 'Recraft V4.1', 'wavespeed',
    'Recraft V4.1 — fast brand illustration.', 0.04, 4,
    'recraft-ai/recraft-v4.1/text-to-image', false, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, false, false, 150, true, '/api/v3/recraft-ai/recraft-v4.1/text-to-image', null),
  ('ws-grok-imagine', 'Grok Imagine', 'wavespeed',
    'xAI Grok Imagine Quality — bold creative T2I.', 0.06, 6,
    'x-ai/grok-imagine-image-quality/text-to-image', true, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, true, false, 160, true, '/api/v3/x-ai/grok-imagine-image-quality/text-to-image', '/api/v3/x-ai/grok-imagine-image-quality/edit'),
  ('ws-mai-image-2-5', 'MAI Image 2.5', 'wavespeed',
    'Microsoft MAI Image 2.5 — Microsoft’s native image model.', 0.05, 5,
    'microsoft/mai-image-2.5/text-to-image', true, true, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K","2K"]'::jsonb, '1:1', '1K', '2K',
    false, true, false, 170, true, '/api/v3/microsoft/mai-image-2.5/text-to-image', '/api/v3/microsoft/mai-image-2.5/edit'),
  ('ws-z-image', 'Z Image', 'wavespeed',
    'WaveSpeed Z Image — ultra-cheap fast T2I.', 0.01, 1,
    'wavespeed-ai/z-image/base', false, false, false, 1,
    '["1:1","3:2","2:3","16:9","9:16"]'::jsonb, '["1K"]'::jsonb, '1:1', '1K', '1K',
    false, false, false, 180, true, '/api/v3/wavespeed-ai/z-image/base', null)
ON CONFLICT (slug) DO UPDATE SET
  is_active = true,
  model_id_api = EXCLUDED.model_id_api,
  provider = EXCLUDED.provider,
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  unit_cost_usd = EXCLUDED.unit_cost_usd,
  credits = EXCLUDED.credits,
  is_premium = EXCLUDED.is_premium,
  is_new = EXCLUDED.is_new,
  is_featured = EXCLUDED.is_featured,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
