
INSERT INTO public.video_models
  (slug, display_name, provider, provider_pool, model_id_api,
   description, unit, cost_per_second_usd, credits_per_second,
   supports_multi_image, max_input_images, supports_start_end_frame, supports_audio,
   supports_first_frame, supports_last_frame, supports_camera_control,
   supports_multi_shot, supports_lipsync, supports_video_editing,
   supported_aspects, supported_resolutions, supported_durations,
   default_aspect, default_resolution, default_duration,
   billing_mode, free_trial_count,
   is_premium, is_new, is_featured, sort_order, is_active, api_version)
VALUES
  ('happyhorse-r2v', 'HappyHorse R2V', 'alibaba', 'dashscope', 'happyhorse-1.0-r2v',
   'Reference-to-Video with up to 9 reference images (#1 globally)',
   'second', 0.28, 28, true, 9, false, false, false, false, true, false, false, false,
   '["16:9","9:16","1:1"]'::jsonb, '["720p","1080p"]'::jsonb, '[5,8,10,15]'::jsonb,
   '16:9', '1080p', 8, 'unlimited_subscriber', 3, true, true, true, 200, true, 'v2'),
  ('happyhorse-i2v', 'HappyHorse I2V', 'alibaba', 'dashscope', 'happyhorse-1.0-i2v',
   'Image-to-Video, first frame, cinematic camera control',
   'second', 0.28, 28, false, 1, true, false, true, false, true, false, false, false,
   '["16:9","9:16","1:1"]'::jsonb, '["720p","1080p"]'::jsonb, '[5,8,10,15]'::jsonb,
   '16:9', '1080p', 8, 'unlimited_subscriber', 3, true, true, false, 210, true, 'v2'),
  ('happyhorse-t2v', 'HappyHorse T2V', 'alibaba', 'dashscope', 'happyhorse-1.0-t2v',
   'Text-to-Video, 1080p with camera control',
   'second', 0.28, 28, false, 0, false, false, false, false, true, false, false, false,
   '["16:9","9:16","1:1"]'::jsonb, '["720p","1080p"]'::jsonb, '[5,8,10,15]'::jsonb,
   '16:9', '1080p', 8, 'unlimited_subscriber', 3, true, true, false, 220, true, 'v2'),
  ('happyhorse-videoedit', 'HappyHorse Video Edit', 'alibaba', 'dashscope', 'happyhorse-1.0-video-edit',
   'Video editing with up to 5 reference images',
   'second', 0.28, 28, true, 5, false, false, false, false, false, false, false, true,
   '["16:9","9:16","1:1"]'::jsonb, '["720p","1080p"]'::jsonb, '[5,8,10]'::jsonb,
   '16:9', '1080p', 5, 'unlimited_subscriber', 3, true, true, false, 230, true, 'v2'),
  ('wan-2-7-i2v', 'Wan 2.7 Image-to-Video', 'alibaba', 'dashscope', 'wan2.7-i2v',
   'Flagship I2V with First+Last frame, lipsync, multi-ref up to 5',
   'second', 0.28, 28, true, 5, true, true, true, true, true, true, true, false,
   '["16:9","9:16","1:1"]'::jsonb, '["720p","1080p"]'::jsonb, '[5,8,10,15]'::jsonb,
   '16:9', '1080p', 8, 'unlimited_subscriber', 3, true, true, true, 240, true, 'v2'),
  ('wan-2-7-t2v', 'Wan 2.7 Text-to-Video', 'alibaba', 'dashscope', 'wan2.7-t2v',
   'Multi-shot T2V with native audio, 1080p',
   'second', 0.28, 28, false, 0, false, true, false, false, true, true, false, false,
   '["16:9","9:16","1:1"]'::jsonb, '["720p","1080p"]'::jsonb, '[5,8,10,15]'::jsonb,
   '16:9', '1080p', 8, 'unlimited_subscriber', 3, true, true, true, 250, true, 'v2'),
  ('wan-2-7-videoedit', 'Wan 2.7 VideoEdit', 'alibaba', 'dashscope', 'wan2.7-videoedit',
   'Local video editing: outfit/background/object swap',
   'second', 0.28, 28, true, 5, false, true, false, false, false, false, false, true,
   '["16:9","9:16","1:1"]'::jsonb, '["720p","1080p"]'::jsonb, '[5,8,10]'::jsonb,
   '16:9', '1080p', 5, 'unlimited_subscriber', 3, true, true, false, 260, true, 'v2'),
  ('wan-2-1-vace-plus', 'Wan 2.1 VACE Plus', 'alibaba', 'dashscope', 'wan2.1-vace-plus',
   'Video repaint, local edit, extension, frame expansion',
   'second', 0.07, 7, true, 5, false, true, false, false, false, false, false, true,
   '["16:9","9:16","1:1"]'::jsonb, '["720p","1080p"]'::jsonb, '[5,8,10]'::jsonb,
   '16:9', '1080p', 5, 'unlimited_subscriber', 3, true, false, false, 270, true, 'v2')
ON CONFLICT (slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  provider = EXCLUDED.provider,
  provider_pool = EXCLUDED.provider_pool,
  model_id_api = EXCLUDED.model_id_api,
  description = EXCLUDED.description,
  is_active = true,
  updated_at = now();
