INSERT INTO public.video_models (
  slug, display_name, provider, provider_pool, model_id_api,
  description, unit, cost_per_second_usd,
  supports_first_frame, supports_last_frame, supports_multi_image, max_input_images,
  supports_audio, supports_voice_clone, supports_camera_control, supports_multi_shot,
  supports_lipsync, supports_video_editing,
  supported_resolutions, supported_durations, default_resolution, default_duration,
  billing_mode, free_trial_count,
  is_premium, is_new, is_featured, sort_order, is_active
) VALUES
('veo-3-0','Veo 3.0','vercel','vercel','google/veo-3.0-generate-001',
 'Google Veo 3.0 — 1080p with native audio','second',0.20,
 true,false,false,0,true,false,true,true,false,false,
 '["720p","1080p"]'::jsonb,'[4,6,8]'::jsonb,'1080p',6,
 'credit_based',3,true,false,false,101,true),
('veo-3-0-fast','Veo 3.0 Fast','vercel','vercel','google/veo-3.0-fast-generate-001',
 'Veo 3.0 fast tier','second',0.10,
 true,false,false,0,true,false,true,true,false,false,
 '["720p","1080p"]'::jsonb,'[4,6,8]'::jsonb,'1080p',6,
 'credit_based',3,true,false,false,111,true),
('kling-v2-5-turbo-i2v','Kling v2.5 Turbo I2V','vercel','vercel','klingai/kling-v2.5-turbo-i2v',
 'First+Last frame, fast tier','second',0.04,
 true,true,false,0,false,false,true,false,false,false,
 '["720p","1080p"]'::jsonb,'[5,8,10]'::jsonb,'720p',5,
 'credit_based',3,true,false,false,141,true),
('kling-v2-5-turbo-t2v','Kling v2.5 Turbo T2V','vercel','vercel','klingai/kling-v2.5-turbo-t2v',
 'Text-to-Video, fast tier','second',0.04,
 false,false,false,0,false,false,true,false,false,false,
 '["720p","1080p"]'::jsonb,'[5,8,10]'::jsonb,'720p',5,
 'credit_based',3,true,false,false,151,true),
('seedance-1-0-pro','Seedance 1.0 Pro','vercel','vercel','bytedance/seedance-v1.0-pro',
 'Seedance 1.0 Pro tier','second',0.02,
 true,false,false,0,false,false,true,false,false,false,
 '["720p","1080p"]'::jsonb,'[5,8,10]'::jsonb,'1080p',5,
 'credit_based',3,true,false,false,121,true),
('seedance-1-0-lite-i2v','Seedance 1.0 Lite I2V','vercel','vercel','bytedance/seedance-v1.0-lite-i2v',
 'Image-to-Video, lite tier','second',0.02,
 true,false,false,0,false,false,true,false,false,false,
 '["720p"]'::jsonb,'[5,8]'::jsonb,'720p',5,
 'credit_based',3,true,false,false,122,true),
('seedance-1-0-lite-t2v','Seedance 1.0 Lite T2V','vercel','vercel','bytedance/seedance-v1.0-lite-t2v',
 'Text-to-Video, lite tier','second',0.02,
 false,false,false,0,false,false,true,false,false,false,
 '["720p"]'::jsonb,'[5,8]'::jsonb,'720p',5,
 'credit_based',3,true,false,false,123,true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.image_models (
  slug, display_name, provider, provider_pool, model_id_api,
  description, unit, unit_cost_usd,
  supports_multi_image, max_input_images,
  supports_image_editing, supports_text_rendering, supports_vector_output,
  supported_aspects, supported_resolutions, default_aspect, default_resolution, max_resolution,
  billing_mode, free_trial_count,
  is_premium, is_new, is_featured, sort_order, is_active
) VALUES
('flux-2-klein-9b','FLUX.2 Klein 9B','vercel','vercel','bfl/flux-2-klein-9b',
 'Smaller, cheaper FLUX.2 tier','image',0.015,
 false,0,false,true,false,
 '["1:1","16:9","9:16","4:3","3:4"]'::jsonb,'["1024"]'::jsonb,'1:1','1024','1024x1024',
 'unlimited_subscriber',3,true,false,false,105,true),
('flux-2-klein-4b','FLUX.2 Klein 4B','vercel','vercel','bfl/flux-2-klein-4b',
 'Tiny FLUX.2 tier','image',0.014,
 false,0,false,true,false,
 '["1:1","16:9","9:16","4:3","3:4"]'::jsonb,'["1024"]'::jsonb,'1:1','1024','1024x1024',
 'unlimited_subscriber',3,true,false,false,106,true),
('flux-2-flex','FLUX.2 Flex','vercel','vercel','bfl/flux-2-flex',
 'Flexible FLUX.2 tier','image',0.06,
 true,4,false,true,false,
 '["1:1","16:9","9:16","4:3","3:4"]'::jsonb,'["2048"]'::jsonb,'1:1','2048','2048x2048',
 'unlimited_subscriber',3,true,false,false,108,true),
('gpt-image-1-mini','GPT Image 1 Mini','vercel','vercel','openai/gpt-image-1-mini',
 'OpenAI cheaper image gen','image',0.02,
 true,4,true,true,false,
 '["1:1","16:9","9:16","3:2"]'::jsonb,'["1024"]'::jsonb,'1:1','1024','1024x1024',
 'unlimited_subscriber',3,true,false,false,141,true)
ON CONFLICT (slug) DO NOTHING;